name: CI/CD Demo
on:
    push:
        branches: [main]

permissions:
    contents: read
    packages: write # needed for GHCR

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 18

            - run: yarn install --frozen-lockfile
            - run: yarn test || echo "no tests yet"

            # Login to GHCR
            - uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            # Build a local image tagged with the commit SHA
            - name: Build image
              run: docker build -t myapp:${{ github.sha }} .

            # Tag and push to GHCR
            - name: Tag & push
              run: |
                  IMAGE=ghcr.io/${{ github.repository_owner }}/myapp
                  docker tag myapp:${{ github.sha }} $IMAGE:latest
                  docker tag myapp:${{ github.sha }} $IMAGE:${{ github.sha }}
                  docker push $IMAGE:latest
                  docker push $IMAGE:${{ github.sha }}

            # (Optional) show images for debugging
            - run: docker images | head -n 10
